package main

//#cgo CFLAGS: -Wno-main-return-type
import "C"

import (
	"os"

	// these modules are generated by glue when we run `roc build.roc` - not using roc glue - don't know how :(
	"host/roc"
)

//export main
func main() {
	exitCode := roc.Main()

	os.Exit(exitCode)
}
